47 terratowns provider (#48)
* #47 wip setting up the skeleton for creating a custom terraform provider

* #47 made changes; trying to start terraform init

* #47 another attempt

* #47 deleted       # source ./bin/build_provider

* #47 now the comment works

* #47 returned to original yml code

* #47 implement terraform provider block in terraform

* #47 new edits

* #47 more edits

* #47 more edits

* #47 edited main.go

* #47 save another edit       source  = "local/providers/terratowns"

* #47 more changes

* #47 copied code from omenking

diff --git a/bin/set_tf_alias b/bin/set_tf_alias
--- a/bin/set_tf_alias
+++ b/bin/set_tf_alias
@@ -1,13 +1,17 @@
 #!/usr/bin/env bash
 
 # Check if the alias already exists in the .bash_profile
-if grep -q 'alias tf="terraform"' ~/.bash_profile; then
-    echo "Alias already exists in .bash_profile."
-else
-    # Add the alias to .bash_profile
+grep -q 'alias tf="terraform"' ~/.bash_profile
+
+# $? is a special variable in bash that holds the exit status of the last command executed
+if [ $? -ne 0 ]; then
+    # If the alias does not exist, append it
     echo 'alias tf="terraform"' >> ~/.bash_profile
-    echo "Alias added to .bash_profile."
+    echo "Alias added successfully."
+else
+    # Inform the user if the alias already exists
+    echo "Alias already exists in .bash_profile."
 fi
 
-# Source the .bash_profile to make the alias available in the current session
+# Optional: source the .bash_profile to make the alias available immediately
 source ~/.bash_profile
